chore: update APY calculations
dopex-io/dopex-api pull request #38
Opened 2022-07-30 22:43 UTC by garyunwin42

2022-07-30 22:45 UTC, garyunwin42 commented on helpers/v2/getSsovApy.js
> -    DPX: { fn: getZeroApy, args: [] },
removing these since they are retired and the try-catch block in `getSsovApy` returns 0 anyway

2022-07-30 22:46 UTC, garyunwin42 commented on helpers/v2/getSsovApy.js
> -        args: ['ETH-WEEKLY-CALLS-SSOV-V3-3', 25],
removing hardcoded rewards and get them from contract instead

2022-07-30 22:55 UTC, garyunwin42 commented on helpers/v2/getSsovApy.js
> -    if (version === 2 && type === 'PUT') {
removing these but open to keeping them if folks think we should keep it

2022-07-30 23:57 UTC, garyunwin42 commented
`yarn test` fails, but I'm not sure what's wrong,
```
yarn test
yarn run v1.22.17
$ jest
 FAIL  test/index.test.js
  ✕ Tests all endpoints (2178 ms)

  ● Tests all endpoints

    Request failed with status code 404



----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.858 s, estimated 3 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2022-07-31 02:06 UTC, garyunwin42 commented on helpers/v2/getSsovApy.js
> +    const totalEpochDepositsInUsd = totalEpochDeposits * priceUnderlying
should have called `getSsovTvl` but I'm not sure why it's not working for me. got some missing provider errors

2022-08-03 10:10 UTC, witherblock requested changes

2022-08-03 10:10 UTC, witherblock commented on README.md
> +
Not required.

2022-08-03 10:10 UTC, witherblock commented on helpers/v2/getSsovApy.js
> +    const totalEpochDepositsInUsd = totalEpochDeposits * priceUnderlying
You don't have the correct .env

2022-08-03 12:49 UTC, garyunwin42 commented
My bad, set up GPG after committing but before push.

2022-08-03 13:42 UTC, witherblock requested changes
So getDopexApy and getDpxRewardsApy are very similar fns with a minor difference. Also using getDopexApy for RDPX will not work since rdpx rewards are in rdpx not dpx.

My suggestion:

Create a single fn call getRewardsApy which queries the staking strat contract for how much rewards and which token and then compute the rewards accordingly.

2022-08-04 17:39 UTC, witherblock approved these changes

2022-08-06 14:24 UTC, merged